### ISSUE TITLE
analytics issues

### ISSUE THREAD

**Issue by dcnb** [uidaholib/main-web-redesign_draft#315]
@evanwill  need analytics code and events!!!

editing to add list: 

- [x] update to [gtag set up](https://support.google.com/analytics/answer/1008080)
- [x] update [cross domain tracking](https://support.google.com/analytics/answer/7476333?hl=en&ref_topic=1008079)
- [ ] set up [outbound links](https://support.google.com/analytics/answer/7478520?hl=en&ref_topic=1008079)
- [ ] discuss [events](https://developers.google.com/analytics/devguides/collection/gtagjs/events) and set up

**Comment by evanwill** [comment]
cross domain details: 

- [ ] update Referral Exclusion List with all cross domains
- [ ] create filtered view to see domains in reports

**Comment by evanwill** [comment]
@dcnb do we still want to load the legacy tracker?

**Comment by dcnb** [comment]
I haven't used it in some time, so no

**Comment by evanwill** [comment]
Okay, commented out the legacy tracker.
