### ISSUE TITLE
SPEC search page update?

### ISSUE THREAD

**Issue by evanwill** [uidaholib/main-web-redesign_draft#327]
[SPEC search page](https://www.lib.uidaho.edu/special-collections/search.php?) is a old PHP app that I don't know anything about-- @dcnb do we want to switch this to Google site search or Lunr?

**Comment by dcnb** [comment]
Yeah, @evanwill . I think either would work. just need to search site content there, which is a little complex with some of the older pages hanging around. We need to check with Ashlyn about what they want to keep accessible and what they don't. 

And if they even want a search feature for their pages when we have a site search anyway ...

**Comment by evanwill** [comment]
the PHP will work for now on the real server--so probably just leave it until we sort out what makes the most sense? 

@dcnb could you create a stub and copy the PHP page into this project so it will build?

**Comment by evanwill** [comment]
we never created this page--
so I just changed all the links to point to site search instead. It doesn't seem like it needs its own thing.
