### ISSUE TITLE
iframe issue on Safari?

### ISSUE THREAD

**Issue by evanwill** [uidaholib/main-web-redesign_draft#354]
it was reported that the form on the [Requests](https://www.lib.uidaho.edu/find/request.html) page does not show up on Safari.

@dcnb or @owikle can you confirm that?

The form is this [qualtrics](https://uidaho.co1.qualtrics.com/jfe/form/SV_agA554AUobIzRKl) in an iframe.

**Comment by owikle** [comment]
I just tried it on Safari and it shows up for me.
