### ISSUE TITLE
FontAwesome

### ISSUE THREAD

**Issue by dcnb** [uidaholib/main-web-redesign_draft#4]
Should we move to font awesome 5? 

Note: I miss glyphicons

**Comment by dcnb** [comment]
Or maybe https://useiconic.com/open/

which Bootstrap recommends.

**Comment by evanwill** [comment]
we are using font awesome 5.0.13. 

there are two options for loading it-- via css+fonts or via js+svg. currently we are using css+fonts. the markup for the actual icons is the same. check the readme for notes about it.

there is a lot more icons in font awesome than iconic. I guess take a look at what icons we are using and see if the iconic ones will work?

**Comment by evanwill** [comment]
p.s. think basically any glyphicon name is still the same in font awesome 5, e.g. 

`<span class="glyphicon glyphicon-align-justify"></span>` 

from your old site is just 

`<span class="fas fa-align-justify"></span>`

on font awesome 5. nothing new to learn!

**Comment by dcnb** [comment]
Whatever I still miss glyphicons

**Comment by evanwill** [comment]
glyphicons live on! closing
