### ISSUE TITLE
Phone Numbers are all over the place

### ISSUE THREAD

**Issue by dcnb** [uidaholib/main-web-redesign_draft#42]

**Comment by evanwill** [comment]
huh?

**Comment by dcnb** [comment]
Phone numbers are inconsistent across the site, some pointing to Reference, some to circ, some to Admin office. Need to look across and make consistent. 

In similar way, addresses are inconsistent. I will look at both these issues.

**Comment by evanwill** [comment]
Maybe just have a error checking task force? go through and click links, check names, check numbers, etc.

**Comment by owikle** [comment]
Jylisa and I can do this. We're almost finished with updating most of the page layouts, so we'll have time to go through next week and check for broken links, missing images, inconsistent numbers, etc.

**Comment by evanwill** [comment]
one thing to keep an eye out for is "&" vs "and", we use & inconsistently, used to drive some people crazy

**Comment by evanwill** [comment]
tracking this issue moved to gdocs
