### ISSUE TITLE
topics of instruction very broken on mobile

### ISSUE THREAD

**Issue by evanwill** [uidaholib/main-web-redesign_draft#436]
- [x] instruction home - topics we teach off screen margin
- [x] topics of instruction - all over lapping makes impossible to click on things in middle, things wider than screen including modals makes impossible to use

**Comment by dcnb** [comment]
Hey @evanwill I think we're working simultaneously.  I totally spelled simultaneously right the first time.

**Comment by dcnb** [comment]
These could use some further tweaking. I'm happy to do that at another time.

**Comment by evanwill** [comment]
I think you got it to working / not broken status, and I fixed the home part, so closing, but always eagerly awaiting further tweaking!
