### ISSUE TITLE
narrow page text layout

### ISSUE THREAD

**Issue by evanwill** [uidaholib/main-web-redesign_draft#437]
for text only pages that look too wide for nice reading on large screens

**Comment by evanwill** [comment]
@owikle I added layout page-narrow using a div with max-width: 700px; (in theme-updates branch). give it a try on a text only page, like about/policies, or spec/about. 

alternatively, could use a column like:

```
<div class="row">
    <div class="col-lg-10">
        {{ content }}
    </div>
</div>
```

then it would be 88% of the width, rather than a max width--which means it would be a bit wider than 700px on very large screens, a bit narrower on mid range screens. 
It seemed like the max-width was better approach, but now feeling like it might look too narrow and to the left on very wide screens (but that might be just unrealistically wide screens?). not sure.

**Comment by owikle** [comment]
@evanwill Ok I played around with this and I think the max-width 700 really does look better on the normal sized and smaller screens. It does look a little bit weird on really wide screens, so I tweaked the css and now when the browser is larger than 1500px the width jumps to 800px. Do you think that helps?

**Comment by evanwill** [comment]
i am thinking now: 
realized the max the page text column can get is 897px no matter what the screen size (due to .container size + col it is in with sidebar). Thus 800px doesn't seem narrow enough, I dropped it to 750px. 
For comparison, CB about pages are max-width 650px, so this is still not aggressively narrow. 
I think it works?

**Comment by owikle** [comment]
Oh good point. I just checked it out, it looks good at 750!

**Comment by dcnb** [comment]
Elements of typographic style, if you want to get "offical" and count:
 “Anything
from 45 to 75 characters is widely regarded as a satisfactory length of
line for a single-column page set in a serifed text face in a text size.
The 66-character line (counting both letters and spaces) is widely regarded
as ideal. For multiple column work, a better average is 40 to 50
characters.â€

**Comment by evanwill** [comment]
Pretty complicated to translate to web because of all the variables of text layout. Seems like you should just be able to say `max-width: 66rem;`, but that doesn't translate correctly, would be much wider than 66 characters.

Butterick says to use "average line length of 45–90 characters, including spaces", or two to three alphabets on a line--which seems like the only practical way to estimate on web page, https://practicaltypography.com/line-length.html

His site uses `abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefgh` = 2.31 alphabets in his font + spacing --> 652px in his layout.

In our website's font and body text size:

two: `abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz` = 440px

three: `abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz` = 660px

So our current page-narrow of 700px is reasonable enough, but could go narrower?

**Comment by evanwill** [comment]
honestly, those line widths are for sort of novel like reading, look really tiny on a website like ours and would lead to excessive scrolling-- so there is a trade off in usability (since people are scanning for info) and theoretical typographic style

**Comment by dcnb** [comment]
ooh I like the layout of practical typography. Really into the side note
recently. especially on the web.

I think I would go narrower than 700px. But really that's just nitpicking.
I thought 650px in CB was right but there are a lot more elements at play
with the lib website and I haven't really looked.

And basically I don't think people read paragraphs at all on library
websites -- they skim, look at buttons, bullets, scatterbrained and sad,
their last good day on earth having been years ago and some sort of twitter
feud pulling at their subconscious.

Or they could be, like, in a pandemic.

**Comment by dcnb** [comment]
I think my catch phrase should be: 'more side note'
 but like from SNL's more cow bell.

Olivia, for you: https://youtu.be/cVsQLlk-T0s

I

**Comment by owikle** [comment]
You think I don't know the cowbell reference? I'm offended.

**Comment by evanwill** [comment]
Butterick is pretty opinionated typography elitist, but pretty amusing-- look through the appendix and commentary.

the site is actually generated by some sort of special static generator (pollen) that he wrote as a sort of programming language in Racket, which is a weird sort of programming language for writing new programming language like things... i don't totally understand.
his book about it: https://beautifulracket.com/

https://practicaltypography.com/how-this-book-was-made.html
https://practicaltypography.com/why-racket-why-lisp.html

if you look at aladore-book, you will see influence, https://evanwill.github.io/aladore-book/text/chapter05.html
including the only free font he says doesn't totally suck, Charter.
