### ISSUE TITLE
Color Consistency

### ISSUE THREAD

**Issue by dcnb** [uidaholib/main-web-redesign_draft#44]
Buttons all need to consistently match up to what they can do

**Comment by dcnb** [comment]
Actions

Search = Yellow
LibGuide = Blue?
Information Modal = ?

Database = Outline yellow
Others ...?

**Comment by evanwill** [comment]
can you make these each as a custom button type like `btn-ui-search`, `btn-ui-guide`, etc? would make it easy to apply and style consistently

**Comment by dcnb** [comment]
right now, just going by color:

search and anything to catalog = btn-pride-gold
libguides = btn-clearwater

database or outside discovery resource = btn-outline-pride-gold

Other possibilities:
Giving = ?
Account it's own color
Hours?

**Comment by dcnb** [comment]
@owikle and @jylisadoney set this out in their google doc.
