### ISSUE TITLE
spec_collections_master scrambled?

### ISSUE THREAD

**Issue by evanwill** [uidaholib/main-web-redesign_draft#452]
@owikle can you look into this? 
I was just searching across the main-web to swap out broken links, but noticed that spec_collections_master.csv appears to be scrambled/corrupted... 

1. some thing weird with columns, they include two each of title, startdate, enddate
2. like half the spreadsheet got out of alignment. Starts around line 483, `spec00482`, the first half of the columns doesn't match the second half, as if the second half is off by three rows. (related to the extra columns??) 

Unbelievable as it might be, the issue is from @dcnb commit 539e1f08be6fab4f0e5024d115aa8b349ecaaf88 
:thinking: 

I am not sure the origins of the dates or the new spreadsheet that scrambled it.

**Comment by evanwill** [comment]
actually @dcnb if you know what is going on could you fix it? 
I was just tagging @owikle before I realized you scrambled it... :wink:

**Comment by evanwill** [comment]
while at it, this record:
"Avista Corporation, Latah County Digital Orthoimage",PG 104, https://cloud.insideidaho.org/webmaps/flash/UofIMoscowCampus/

link should be updated to: https://uidaho.maps.arcgis.com/home/group.html?id=1954ee9ea97b49f1b05f3b294cc9a59d&view=list&searchTerm=avista#content

**Comment by owikle** [comment]
I'm not sure the best way to fix this without rolling back the work spec did on the subjects in the spreadsheet... @dcnb, which start date/end date columns are correct?

**Comment by evanwill** [comment]
sounds like it makes sense to just go back to spec version and pull in the dates again, since the current version in this repo is so scrambled. 
@dcnb what is the source of the start date/end date?

**Comment by dcnb** [comment]
It was not that scrambled. Just saying. Courtney saw it pretty quick.

**Comment by evanwill** [comment]
@dcnb like it says at the start of the issue, "off by 3 rows" and duplicate columns (= pretty scrambled), but i just wanted someone who knew what was going on to actually check it out to ensure we aren't introducing new lasting anomalies to the data by a quick fix... 
did you push??

**Comment by dcnb** [comment]
pushed. Not put on main site. Please do that.
