### ISSUE TITLE
clarify use of librarian titles / streamline directory pages

### ISSUE THREAD

**Issue by evanwill** [uidaholib/main-web-redesign_draft#472]
librarians are listed on several different directory style pages. Each differs in listing title vs. liaison area.

- https://www.lib.uidaho.edu/about/directory.html
- https://www.lib.uidaho.edu/about/librarians.html
- https://www.lib.uidaho.edu/about/liaisons.html
- https://www.lib.uidaho.edu/help/research.html

**Comment by dcnb** [comment]
My two cents:

We should simplify the discovery for people and then have individual pages
for each librarian. I'm guessing most people are searching through google
anyway, so having better meta tags etc. might be your most effective
method.

**Comment by evanwill** [comment]
model after main uni faculty profile pages
