### ISSUE TITLE
Link rot: find->geospatial->Teaching & Learning->Working with GIS data

### ISSUE THREAD

**Issue by hanwendong1** [uidaholib/main-web-redesign_draft#497]

**Comment by evanwill** [comment]
@b-godfrey the link @hanwendong1 is referring to is on the page https://www.lib.uidaho.edu/find/geospatial/#teaching
in the Teaching & Learning box, 

"Working with GIS data" linking to 
https://ischoolonline.syr.edu/blog/gis-data/
which is broken.

Should I delete it, or did you have a replacement resource? Thanks!

**Comment by b-godfrey** [comment]
Yes, it should point here:  https://onlinegrad.syracuse.edu/blog/gis-data/

I updated the link awhile ago on https://www.lib.uidaho.edu/find/geospatial/software.html but overlooked https://www.lib.uidaho.edu/find/geospatial/#teaching

Thanks,
Bruce
