### ISSUE TITLE
Workshop Resources link rot 

### ISSUE THREAD

**Issue by hanwendong1** [uidaholib/main-web-redesign_draft#525]
Machine Learning in Python - part 1/3 - Data Hub Tech Talk -> Notebook

**Comment by evanwill** [comment]
@hanwendong1 thanks for pointing out--> just checked it, the link isn't actually broken, the server is! Apparently our server now is only accepting requests with a set of known extensions (seems like basically .html, .css, .js, .txt, .xlsx, .csv, .tsv, .json, and some fonts). If your url ends with an extension that isn't that, it redirects you to 404... 
@owikle @dcnb not sure if it is worth bringing this up to ITS and getting a few more files types added? This was what was messing up our font delivery earlier, but I didn't realize it was quite so restrictive. But FYI for working around, for code, data, or non-normal extensions, best option is to zip the files (.zip is accepted).
