### ISSUE TITLE
Reserves Editing

### ISSUE THREAD

**Issue by shortgoblin** [uidaholib/main-web-redesign_draft#541]
- [x] Get rid of electronic reserve references
- [x] Simplify content (read: text) on Reserve pages
- [x] Condense policies
- [x] Condense FAQ (and how-to?)
- [x] Decrease pages as much as possible

Might need to speak with Kristin about relevant copyright/if we need copyright on the pages at all. Could link to copyright.
- chose to link to copyright and keep reference to FERPA

**Comment by shortgoblin** [comment]
really condensing everything a lot, I think it almost might make more sense to get the reserves page down to just one page than keeping any extra pages

**Comment by shortgoblin** [comment]
@evanwill would it be too much work to shave off all the extra pages and just turn the "Course Reserves" label into the main (and only) page for reserves? Considering how much I'm cutting out, it doesn't really make sense to me to leave any of the extra pages at this point

**Comment by evanwill** [comment]
@shortgoblin the side nav is set up in "_data/config_pagesnav.yml", so easy to change up (but the set up is a bit weird, so I normally do that--we can talk about it soon, but know that it can be changed!).

**Comment by shortgoblin** [comment]
@evanwill great! I've gotten everything smashed into one page so theoretically we're good to go there

**Comment by shortgoblin** [comment]
@evanwill a second set of eyes okay'd my changes, and today I went through and updated the links (I believe I caught all of the ones from the main page and from secondary pages) and updated the policies page. I thin kit's as good as we're going to get at this point - what should I do next?

**Comment by evanwill** [comment]
@shortgoblin you can go to your branch and open a pull request if you want to move it to next step. I haven't had a chance to take a look, but hopefully will sometime this week!
